site_name: Godot Oculus Platform
site_url: https://decacis.github.io/godot_oculus_platform
site_description: An implementation of the Oculus Platform SDK for the Godot Engine.
site_dir: godot_oculus_platform
copyright: Copyright &copy; 2023-present Daniel Castellanos and contributors (CC BY 3.0)
repo_url: https://github.com/decacis/godot_oculus_platform
edit_uri: edit/gh-pages-source/docs/
nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Download: download.md
  - Examples: examples.md
  - Build: build.md
  - Functions:
    - Initialization: 'functions/initialization.md'
    - Application: 'functions/application.md'
    - Abuse Report: 'functions/abuse-report.md'
    - User: 'functions/user.md'
    - Achievements: 'functions/achievements.md'
    - In-App Purchases: 'functions/in-app-purchases.md'
    - Asset Files: 'functions/asset-files.md'
    - Leaderboards: 'functions/leaderboards.md'
    - Challenges: 'functions/challenges.md'
    - Group Presence: 'functions/group-presence.md'
    - Media: 'functions/media.md'
    - User Age Category: 'functions/user-age-category.md'
    - Attestation API: 'functions/attestation-api.md'
  - Misc:
    - About previous_page_url and next_page_url: 'misc/about-previous_page_url-and-next_page_url.md'
theme:
  name: material
  logo: assets/gdop_logo_w.svg
  favicon: assets/gdop_256.png
  palette:
    - scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.view
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - navigation.footer
markdown_extensions:
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details